#!/usr/bin/env bash
set -euo pipefail

PROJECT=/public/home/xinxi/wxtian/WXTIAN/PINN/deepxde/boundary_uncertainty_pinn
RUN_STAMP=${RUN_STAMP:-$(date +%Y%m%d_%H%M%S)}
GROUP=${GROUP:-01.AnalyticalCore8Smoke}
ITERATIONS=${ITERATIONS:-3000}
DISPLAY_EVERY=${DISPLAY_EVERY:-1000}
CHECKPOINT_EVERY=${CHECKPOINT_EVERY:-5000}
NUM_DOMAIN=${NUM_DOMAIN:-2000}
NUM_BOUNDARY=${NUM_BOUNDARY:-600}
OBS_COUNT=${OBS_COUNT:-120}
VAL_COUNT=${VAL_COUNT:-500}
TEST_NX=${TEST_NX:-121}
TEST_NY=${TEST_NY:-61}
ANCHOR_COUNT=${ANCHOR_COUNT:-4}
REACTION_POINTS=${REACTION_POINTS:-80}
WIDTH=${WIDTH:-56}
DEPTH=${DEPTH:-4}
MATERIAL_WIDTH=${MATERIAL_WIDTH:-56}
MATERIAL_DEPTH=${MATERIAL_DEPTH:-4}
WIDE_WIDTH=${WIDE_WIDTH:-96}
WIDE_DEPTH=${WIDE_DEPTH:-5}
BOUNDARY_MODES=${BOUNDARY_MODES:-1}
SEED=${SEED:-42}
CONDA_ENV=${CONDA_ENV:-pytorch2.1w2}
PHYSICS_WEIGHT=${PHYSICS_WEIGHT:-1.0}
MOMENTUM_WEIGHT=${MOMENTUM_WEIGHT:-}
CONSTITUTIVE_WEIGHT=${CONSTITUTIVE_WEIGHT:-}
BOUNDARY_WEIGHT=${BOUNDARY_WEIGHT:-1.0}
OBS_WEIGHT=${OBS_WEIGHT:-1.0}
OBS_MATERIAL_WEIGHT=${OBS_MATERIAL_WEIGHT:-20.0}
OBS_BOUNDARY_WEIGHT=${OBS_BOUNDARY_WEIGHT:-20.0}
ANCHOR_WEIGHT_DEFAULT=${ANCHOR_WEIGHT:-1.0}
REACTION_WEIGHT_DEFAULT=${REACTION_WEIGHT:-5.0}
GRADIENT_DIAGNOSTIC_PERIOD=${GRADIENT_DIAGNOSTIC_PERIOD:-0}
EQUILIBRIUM_FORM=${EQUILIBRIUM_FORM:-direct}
REACTION_FORM=${REACTION_FORM:-constitutive}
EVAL_CHECKPOINT=${EVAL_CHECKPOINT:-best}

CASES=(A0 A1 A2 A3 A4 A5 A6 A7)
RUN_NAMES=(A0 A1 A2 A3 A4 A5 A6 A7)
OLD_CASES=(A0 A1 A2 A3 A5 A9 A14 A15)
NODES=(
  10.6.234.27 10.6.234.27
  10.6.234.28 10.6.234.28
  10.6.234.29 10.6.234.29
  10.6.234.30 10.6.234.30
)
DEVICES=(0 1 0 1 0 1 0 1)

for i in "${!CASES[@]}"; do
  CASE=${CASES[$i]}
  RUN_NAME=${RUN_NAMES[$i]}
  OLD_CASE=${OLD_CASES[$i]}
  NODE=${NODES[$i]}
  DEVICE_INDEX=${DEVICES[$i]}
  ANCHOR_WEIGHT=$ANCHOR_WEIGHT_DEFAULT
  REACTION_WEIGHT=$REACTION_WEIGHT_DEFAULT
  RUN_NOTE="UnifiedAnalyticalCoreSmoke_new_${CASE}_old_${OLD_CASE}_BCompatiblePoints_DirectConstitutive"
  RUN_DIR="$PROJECT/exp/$GROUP/$RUN_NAME"
  SCREEN_NAME="bupinn_${GROUP}_${RUN_NAME}_${RUN_STAMP}"
  remote_env="CASE=$CASE RUN_NAME=$RUN_NAME RUN_STAMP=$RUN_STAMP DEVICE_INDEX=$DEVICE_INDEX ITERATIONS=$ITERATIONS DISPLAY_EVERY=$DISPLAY_EVERY CHECKPOINT_EVERY=$CHECKPOINT_EVERY NUM_DOMAIN=$NUM_DOMAIN NUM_BOUNDARY=$NUM_BOUNDARY OBS_COUNT=$OBS_COUNT VAL_COUNT=$VAL_COUNT TEST_NX=$TEST_NX TEST_NY=$TEST_NY ANCHOR_COUNT=$ANCHOR_COUNT REACTION_POINTS=$REACTION_POINTS WIDTH=$WIDTH DEPTH=$DEPTH MATERIAL_WIDTH=$MATERIAL_WIDTH MATERIAL_DEPTH=$MATERIAL_DEPTH WIDE_WIDTH=$WIDE_WIDTH WIDE_DEPTH=$WIDE_DEPTH BOUNDARY_MODES=$BOUNDARY_MODES SEED=$SEED GROUP=$GROUP CONDA_ENV=$CONDA_ENV PHYSICS_WEIGHT=$PHYSICS_WEIGHT MOMENTUM_WEIGHT=$MOMENTUM_WEIGHT CONSTITUTIVE_WEIGHT=$CONSTITUTIVE_WEIGHT BOUNDARY_WEIGHT=$BOUNDARY_WEIGHT OBS_WEIGHT=$OBS_WEIGHT OBS_MATERIAL_WEIGHT=$OBS_MATERIAL_WEIGHT OBS_BOUNDARY_WEIGHT=$OBS_BOUNDARY_WEIGHT ANCHOR_WEIGHT=$ANCHOR_WEIGHT REACTION_WEIGHT=$REACTION_WEIGHT GRADIENT_DIAGNOSTIC_PERIOD=$GRADIENT_DIAGNOSTIC_PERIOD EQUILIBRIUM_FORM=$EQUILIBRIUM_FORM REACTION_FORM=$REACTION_FORM EVAL_CHECKPOINT=$EVAL_CHECKPOINT FORMAL_CORE_MAP=1 RUN_NOTE='$RUN_NOTE'"
  echo "launch smoke new_case=$CASE old_case=$OLD_CASE node=$NODE device=$DEVICE_INDEX run_dir=$RUN_DIR"
  ssh "$NODE" "set -euo pipefail; cd '$PROJECT'; \
    if [ -e '$RUN_DIR' ]; then echo 'ERROR: run directory already exists: $RUN_DIR' >&2; exit 2; fi; \
    if screen -ls | grep -q '[.]$SCREEN_NAME[[:space:]]'; then echo 'ERROR: screen already exists: $SCREEN_NAME' >&2; exit 2; fi; \
    chmod +x hpc/run_decoupled_onecase_lf.sh; \
    screen -dmS '$SCREEN_NAME' bash -lc '$remote_env bash hpc/run_decoupled_onecase_lf.sh'"
done

echo "run_stamp=$RUN_STAMP"
echo "group=$GROUP"
echo "runs=A0 A1 A2 A3 A4 A5 A6 A7"
echo "eta=about 20-40 minutes for smoke; verify process, log timestamp, and step growth"
