#!/usr/bin/env bash
set -euo pipefail

PROJECT=/public/home/xinxi/wxtian/WXTIAN/PINN/deepxde/boundary_uncertainty_pinn
RUN_STAMP=${RUN_STAMP:-$(date +%Y%m%d_%H%M%S)}
GROUP=${GROUP:-00.Smoke}
ITERATIONS=${ITERATIONS:-3000}
DISPLAY_EVERY=${DISPLAY_EVERY:-300}
NUM_DOMAIN=${NUM_DOMAIN:-500}
NUM_BOUNDARY=${NUM_BOUNDARY:-160}
OBS_GRID=${OBS_GRID:-8}
VAL_GRID=${VAL_GRID:-21}
TEST_GRID=${TEST_GRID:-51}
ANCHOR_COUNT=${ANCHOR_COUNT:-4}
REACTION_POINTS=${REACTION_POINTS:-80}
WIDTH=${WIDTH:-48}
DEPTH=${DEPTH:-3}
MATERIAL_WIDTH=${MATERIAL_WIDTH:-48}
MATERIAL_DEPTH=${MATERIAL_DEPTH:-3}
WIDE_WIDTH=${WIDE_WIDTH:-80}
WIDE_DEPTH=${WIDE_DEPTH:-4}
BOUNDARY_MODES=${BOUNDARY_MODES:-1}
SEED=${SEED:-42}
CONDA_ENV=${CONDA_ENV:-pytorch2.1w2}
PHYSICS_WEIGHT=${PHYSICS_WEIGHT:-1.0}
MOMENTUM_WEIGHT=${MOMENTUM_WEIGHT:-}
CONSTITUTIVE_WEIGHT=${CONSTITUTIVE_WEIGHT:-}
BOUNDARY_WEIGHT=${BOUNDARY_WEIGHT:-1.0}
OBS_WEIGHT=${OBS_WEIGHT:-1.0}
OBS_MATERIAL_WEIGHT=${OBS_MATERIAL_WEIGHT:-1.0}
OBS_BOUNDARY_WEIGHT=${OBS_BOUNDARY_WEIGHT:-1.0}
ANCHOR_WEIGHT=${ANCHOR_WEIGHT:-1.0}
REACTION_WEIGHT=${REACTION_WEIGHT:-1.0}
GRADIENT_DIAGNOSTIC_PERIOD=${GRADIENT_DIAGNOSTIC_PERIOD:-0}
EQUILIBRIUM_FORM=${EQUILIBRIUM_FORM:-mixed}
REACTION_FORM=${REACTION_FORM:-stress}
EVAL_CHECKPOINT=${EVAL_CHECKPOINT:-best}

CASES=(A0 A1 A2 A3 A4 A5 A6 A7 A8 A9 A10 A11 A12 A13 A14 A15)
NODES=(
  10.6.234.22 10.6.234.22
  10.6.234.23 10.6.234.23
  10.6.234.24 10.6.234.24
  10.6.234.25 10.6.234.25
  10.6.234.27 10.6.234.27
  10.6.234.28 10.6.234.28
  10.6.234.29 10.6.234.29
  10.6.234.30 10.6.234.30
)
DEVICES=(0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1)

for i in "${!CASES[@]}"; do
  CASE=${CASES[$i]}
  NODE=${NODES[$i]}
  DEVICE_INDEX=${DEVICES[$i]}
  RUN_NAME=${RUN_NAME_PREFIX:-}${CASE}
  RUN_DIR="$PROJECT/exp/$GROUP/$RUN_NAME"
  SCREEN_NAME="bupinn_${CASE}_${RUN_STAMP}"
  remote_env="CASE=$CASE RUN_NAME=$RUN_NAME RUN_STAMP=$RUN_STAMP DEVICE_INDEX=$DEVICE_INDEX ITERATIONS=$ITERATIONS DISPLAY_EVERY=$DISPLAY_EVERY NUM_DOMAIN=$NUM_DOMAIN NUM_BOUNDARY=$NUM_BOUNDARY OBS_GRID=$OBS_GRID VAL_GRID=$VAL_GRID TEST_GRID=$TEST_GRID ANCHOR_COUNT=$ANCHOR_COUNT REACTION_POINTS=$REACTION_POINTS WIDTH=$WIDTH DEPTH=$DEPTH MATERIAL_WIDTH=$MATERIAL_WIDTH MATERIAL_DEPTH=$MATERIAL_DEPTH WIDE_WIDTH=$WIDE_WIDTH WIDE_DEPTH=$WIDE_DEPTH BOUNDARY_MODES=$BOUNDARY_MODES SEED=$SEED GROUP=$GROUP CONDA_ENV=$CONDA_ENV PHYSICS_WEIGHT=$PHYSICS_WEIGHT MOMENTUM_WEIGHT=$MOMENTUM_WEIGHT CONSTITUTIVE_WEIGHT=$CONSTITUTIVE_WEIGHT BOUNDARY_WEIGHT=$BOUNDARY_WEIGHT OBS_WEIGHT=$OBS_WEIGHT OBS_MATERIAL_WEIGHT=$OBS_MATERIAL_WEIGHT OBS_BOUNDARY_WEIGHT=$OBS_BOUNDARY_WEIGHT ANCHOR_WEIGHT=$ANCHOR_WEIGHT REACTION_WEIGHT=$REACTION_WEIGHT GRADIENT_DIAGNOSTIC_PERIOD=$GRADIENT_DIAGNOSTIC_PERIOD EQUILIBRIUM_FORM=$EQUILIBRIUM_FORM REACTION_FORM=$REACTION_FORM EVAL_CHECKPOINT=$EVAL_CHECKPOINT"
  echo "launch case=$CASE run_name=$RUN_NAME node=$NODE device=$DEVICE_INDEX run_dir=$RUN_DIR"
  ssh "$NODE" "set -euo pipefail; cd '$PROJECT'; \
    if [ -e '$RUN_DIR' ]; then echo 'ERROR: run directory already exists: $RUN_DIR' >&2; exit 2; fi; \
    if screen -ls | grep -q '[.]$SCREEN_NAME[[:space:]]'; then echo 'ERROR: screen already exists: $SCREEN_NAME' >&2; exit 2; fi; \
    chmod +x hpc/run_decoupled_onecase_lf.sh; \
    screen -dmS '$SCREEN_NAME' bash -lc '$remote_env bash hpc/run_decoupled_onecase_lf.sh'"
done

echo "run_stamp=$RUN_STAMP"
echo "group=$GROUP"
if [ "$ITERATIONS" -le 5000 ]; then
  echo "eta=about 20-60 minutes for 16-case smoke, depending on dynamic figure overhead"
else
  echo "eta=PFNN/split cases about 4-8 hours; decoupled cases should be much faster than the previous unoptimized version but need smoke timing"
fi
