#!/usr/bin/env bash
set -euo pipefail

PROJECT=/public/home/xinxi/wxtian/WXTIAN/PINN/deepxde/boundary_uncertainty_pinn
NODE=${NODE:-10.6.234.22}
DEVICE_INDEX=${DEVICE_INDEX:-0}
CASE=${CASE:-learnable_A_anchor}
RUN_NAME=${RUN_NAME:-smoke_${CASE}_$(date +%Y%m%d_%H%M%S)}
SCREEN_NAME=${SCREEN_NAME:-bupinn_smoke_${RUN_NAME}}
RUN_DIR=$PROJECT/exp/00.Smoke/$RUN_NAME

ITERATIONS=${ITERATIONS:-800}
DISPLAY_EVERY=${DISPLAY_EVERY:-100}
NUM_DOMAIN=${NUM_DOMAIN:-500}
NUM_BOUNDARY=${NUM_BOUNDARY:-160}
OBS_GRID=${OBS_GRID:-8}
TEST_GRID=${TEST_GRID:-101}
ANCHOR_COUNT=${ANCHOR_COUNT:-4}
REACTION_POINTS=${REACTION_POINTS:-100}
WIDTH=${WIDTH:-64}
DEPTH=${DEPTH:-4}
SEED=${SEED:-42}

remote_env="DEVICE_INDEX=$DEVICE_INDEX CASE=$CASE RUN_NAME=$RUN_NAME RUN_DIR=$RUN_DIR ITERATIONS=$ITERATIONS DISPLAY_EVERY=$DISPLAY_EVERY NUM_DOMAIN=$NUM_DOMAIN NUM_BOUNDARY=$NUM_BOUNDARY OBS_GRID=$OBS_GRID TEST_GRID=$TEST_GRID ANCHOR_COUNT=$ANCHOR_COUNT REACTION_POINTS=$REACTION_POINTS WIDTH=$WIDTH DEPTH=$DEPTH SEED=$SEED"

ssh "$NODE" "set -euo pipefail; mkdir -p '$RUN_DIR/txt'; cd '$PROJECT'; chmod +x hpc/run_deepxde_smoke.sh; screen -dmS '$SCREEN_NAME' bash -lc '$remote_env bash hpc/run_deepxde_smoke.sh'"

echo "NODE=$NODE"
echo "DEVICE_INDEX=$DEVICE_INDEX"
echo "SCREEN_NAME=$SCREEN_NAME"
echo "RUN_DIR=$RUN_DIR"
echo "ITERATIONS=$ITERATIONS"
echo "NUM_DOMAIN=$NUM_DOMAIN"
echo "NUM_BOUNDARY=$NUM_BOUNDARY"
echo "OBS_GRID=$OBS_GRID"
echo "TEST_GRID=$TEST_GRID"
echo "ANCHOR_COUNT=$ANCHOR_COUNT"
echo "REACTION_POINTS=$REACTION_POINTS"
echo "ETA=smoke expected 5-15 minutes depending on GPU queue/device state"
